### ISSUE TITLE
Setup storybook

### ISSUE THREAD

**Issue by tkdeshpande** [tkdeshpande/tkdeshpande.github.io#9]
## Todos
- [ ] 📦 Initialize a new Storybook with Webpack 5
- [ ] 📑 Create stories for Next.js pages
- [ ] 🌎 Import shared, global styles in preview.js
- [ ] ⬇️ De-optimize Next Image for use in Stories

Ref: [storybook-and-next-js](https://storybook.js.org/blog/get-started-with-storybook-and-next-js)
